In [300]:
import numpy as np
import pandas as pd

In [301]:
lluv1907=pd.read_csv("lluv1907.csv")
lluv1908=pd.read_csv("lluv1908.csv")
lluv1909=pd.read_csv("lluv1909.csv")
lluv1910=pd.read_csv("lluv1910.csv")
lluv1911=pd.read_csv("lluv1911.csv")
lluv1912=pd.read_csv("lluv1912.csv")

tmax09=pd.read_csv("201909010000TMax.csv")
tmax10=pd.read_csv("201910010000TMax.csv")
tmax11=pd.read_csv("201911010000TMax.csv")
tmed09=pd.read_csv("201909010000TMed.csv")
tmed10=pd.read_csv("201910010000TMed.csv")
tmed11=pd.read_csv("201911010000TMed.csv")
tmin09=pd.read_csv("201909010000TMin.csv")
tmin10=pd.read_csv("201910010000TMin.csv")
tmin11=pd.read_csv("201911010000TMin.csv")

print('Tamaños de dataframes')
print('lluv1907:', lluv1907.shape) #JULIO
print('lluv1908:', lluv1908.shape) #AGOSTO
print('lluv1909:', lluv1909.shape) # ...
print('lluv1910:', lluv1910.shape)
print('lluv1911:', lluv1911.shape)
print('lluv1912:', lluv1912.shape)

print('tmax09:', tmax09.shape) #SEPTIEMBRE
print('tmax10:', tmax10.shape) #OCTUBRE
print('tmax11:', tmax11.shape) #NOVIEMBRE
print('tmed09:', tmed09.shape)
print('tmed10:', tmed10.shape)
print('tmed11:', tmed11.shape)
print('tmin09:', tmin09.shape)
print('tmin10:', tmin10.shape)
print('tmin11:', tmin11.shape)

Tamaños de dataframes
lluv1907: (1290, 6)
lluv1908: (1504, 6)
lluv1909: (1541, 6)
lluv1910: (1566, 6)
lluv1911: (1653, 6)
lluv1912: (1595, 6)
tmax09: (1267, 6)
tmax10: (1197, 6)
tmax11: (1292, 6)
tmed09: (1267, 6)
tmed10: (1197, 6)
tmed11: (1292, 6)
tmin09: (1267, 6)
tmin10: (1197, 6)
tmin11: (1292, 6)

Con ayuda del comando merge se pueden unir bases de datos desechando aquellos que están fuera de la intersección. Se tienen los datos de temperaturas mínimas, medias y máximas de 3 meses, primero se crean 3 tablas, una para cada mes, uniendo con el comando pd.merge las bases de datos correspondientes a la temperatura mínima, media y máxima de cada mes. Después, estas 3 tablas se unen para formar la tabla 'merget'.

In [302]:
mergedt09=pd.merge(pd.merge(tmin09,tmed09),tmax09)
mergedt09.index=range(1,mergedt09.shape[0]+1)
mergedt09=mergedt09.rename(columns={'Est':'Estación','Tmin':'Min09','Tmed':'Med09','Tmax':'Max09'})

mergedt10=pd.merge(pd.merge(tmin10,tmed10),tmax10)
mergedt10.index=range(1,mergedt10.shape[0]+1)
mergedt10=mergedt10.rename(columns={'Est':'Estación','Tmin':'Min10','Tmed':'Med10','Tmax':'Max10'})

mergedt11=pd.merge(pd.merge(tmin11,tmed11),tmax11)
mergedt11.index=range(1,mergedt11.shape[0]+1)
mergedt11=mergedt11.rename(columns={'Est':'Estación','Tmin':'Min11','Tmed':'Med11','Tmax':'Max11'})

mergedt=pd.merge(pd.merge(mergedt09,mergedt10),mergedt11)
mergedt

,Lon,Lat,Clave,Edo,Estación,Min09,Med09,Max09,Min10,Med10,Max10,Min11,Med11,Max11
0,-102.37,21.78,NGRAG,AGS,El Niagara Ags.,13.2,20.5,27.9,12.3,19.5,26.8,9.5,17.9,26.3
1,-102.79,21.81,MNLAG,AGS,Media Luna Ags.,14.2,22.0,29.8,12.9,20.6,28.2,10.4,19.0,27.6
2,-102.71,21.85,CALVILLO,AGS,Calvillo Ags. SMN*,14.7,22.5,30.2,13.3,21.5,29.7,10.6,19.2,27.7
3,-102.29,21.85,OBSAG,AGS,Observatorio de Aguascalientes Ags.,15.1,22.1,29.2,13.7,21.0,28.2,10.8,18.3,25.8
4,-102.00,21.90,CNSAG,AGS,Los Conos Ags.,12.1,19.4,26.7,11.5,18.8,26.1,8.9,17.1,25.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,-103.09,22.93,GJAZC,ZAC,General Joaqu�n Amaro Zac.,10.5,16.3,22.1,10.2,16.2,22.1,8.1,14.1,20.1
1121,-101.39,24.62,CORZC,ZAC,Concepci�n del Oro Zac.,14.6,20.6,26.5,14.1,20.6,27.1,10.2,17.0,23.7
1122,-102.25,22.44,LMOZC,ZAC,Luis Moya Zac.,13.1,21.2,29.2,11.9,20.3,28.8,9.4,17.1,24.8
1123,-102.46,22.49,GRCZC,ZAC,Genaro Codina Zac.,9.6,15.6,21.6,8.4,14.9,21.4,5.2,12.9,20.7
1124,-102.57,22.78,ZACATECASob,ZAC,Observatorio de Zacatecas Zac. SMN*,12.5,16.1,19.7,12.2,16.0,19.8,10.5,14.0,17.6

Se unen los datos de las tablas de lluvia del último semestre de 2019.

In [303]:
mergedlluv=pd.merge(pd.merge(pd.merge(pd.merge(pd.merge(lluv1907,lluv1908),lluv1909),lluv1910),lluv1911),lluv1912)
mergedlluv.index=range(1,mergedlluv.shape[0]+1)
mergedlluv=mergedlluv.rename(columns={'oct-19':'OCT','nov-19':'NOV','dic-19':'DIC'})    
mergedlluv

,LON,LAT,EDO,CLAVE,ESTACION,JUL,AGO,SEP,OCT,NOV,DIC
1,-102.712222,21.849167,AGS,CALVILLO,"Calvillo, Ags. SMN*",18.3,105.47,54.97,22.23,29.8,5.78
2,-102.676944,21.997500,AGS,CDRAG,"La Codorniz, Ags.",139.0,156.30,128.00,64.00,35.8,7.00
3,-102.000000,21.896389,AGS,CNSAG,"Los Conos, Ags.",100.4,160.73,59.74,40.62,46.8,20.90
4,-102.296667,22.362778,AGS,CSOAG,"Cos�o, Ags.",39.3,40.33,35.24,29.34,41.7,27.01
5,-102.356944,22.121667,AGS,JCQAG,"Jocoque, Ags.",43.1,108.32,67.33,23.53,18.9,15.20
...,...,...,...,...,...,...,...,...,...,...,...
981,-103.879722,23.471944,ZAC,TCHZC,"Chalchihuites, Zac.",173.0,72.00,93.50,16.50,116.0,23.01
982,-103.309444,21.773611,ZAC,TLLZC,"Tlaltenango, Zac.",227.8,112.91,85.23,85.11,49.4,8.60
983,-101.715833,22.347500,ZAC,VHGZC,"Villa Hidalgo, Zac.",72.4,69.70,30.13,30.80,56.2,26.71
984,-103.337500,21.588889,ZAC,VILZC,"Jos� Mar�a Morelos, Zac.",213.2,188.80,71.40,125.20,66.6,13.80
985,-102.576667,22.761389,ZAC,ZACZC,"Zacatecas, Zac.",59.0,35.42,121.10,43.31,73.7,31.51